---
abstract: 'Find the differences between two arrays'
author:
  - 'Daisuke Murase <typester@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.011, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Array-Diff
requires:
  Algorithm::Diff: '1.19'
  Class::Accessor::Fast: '0'
  base: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilb/array-diff-perl
  repository: https://github.com/neilb/array-diff-perl.git
version: '0.09'
x_serialization_backend: 'YAML::Tiny version 1.62'
